const cities = [
  {
    id: 1,
    city: "Paris",
    country: "France",
    image: "imgs/paris.jpeg",
    flightPrice: "250",
    hotelPrice: "130",
  },
  {
    id: 2,
    city: "Bangkok",
    country: "Thailand",
    image: "/imgs/bangkok.jpeg",
    flightPrice: "249",
    hotelPrice: "139",
  },
  {
    id: 3,
    city: "London",
    country: "United Kingdom",
    image: "imgs/london.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 4,
    city: "Dubai",
    country: "UAE",
    image: "imgs/dubai.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 5,
    city: "Singapore",
    country: "Singapore",
    image: "imgs/singapore.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 6,
    city: "Kuala Lumpur",
    country: "Malaysia",
    image: "imgs/kualalumpur.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 7,
    city: "New York",
    country: "USA",
    image: "imgs/newyork.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 8,
    city: "Istanbul",
    country: "Turkey",
    image: "imgs/istanbul.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 9,
    city: "Tokyo",
    country: "Japan",
    image: "imgs/tokyo.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 10,
    city: "Seoul",
    country: "South Korea",
    image: "imgs/seoul.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 11,
    city: "Phuket",
    country: "Thailand",
    image: "imgs/phuket.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 12,
    city: "Milan",
    country: "Italy",
    image: "imgs/milan.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 13,
    city: "Barcelona",
    country: "Spain",
    image: "imgs/barcelona.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 14,
    city: "Bali",
    country: "Indonesia",
    image: "imgs/bali.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 15,
    city: "Hong Kong",
    country: "China",
    image: "imgs/hongkong.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 16,
    city: "Delhi",
    country: "India",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 17,
    city: "Cairo",
    country: "Egypt",
    image: "imgs/cairo.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 18,
    city: "Athens",
    country: "Greece",
    image: "imgs/athens.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 19,
    city: "Moscow",
    country: "Russia",
    image: "imgs/moscow.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 20,
    city: "Florence",
    country: "Italy",
    image: "imgs/florence.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 21,
    city: "Dublin",
    country: "Ireland",
    image: "imgs/dublin.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 22,
    city: "Chennai",
    country: "India",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 23,
    city: "Orlando",
    country: "USA",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 24,
    city: "Madrid",
    country: "Spain",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 25,
    city: "Jaipur",
    country: "India",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 26,
    city: "Venice",
    country: "Italy",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 27,
    city: "Ho Chi Minh City",
    country: "Vietnam",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 28,
    city: "Johannesburg",
    country: "South Africa",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 29,
    city: "Johor Bahru",
    country: "Malaysia",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 30,
    city: "Berlin",
    country: "Germany",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 31,
    city: "Cancun",
    country: "Mexico",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 32,
    city: "Vienna",
    country: "Austria",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 33,
    city: "Osaka",
    country: "Japan",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 34,
    city: "Agra",
    country: "India",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 35,
    city: "Las Vegas",
    country: "USA",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
  {
    id: 36,
    city: "Amsterdam",
    country: "Netherland",
    image: "imgs/delhi.jpeg",
    flightPrice: "",
    hotelPrice: "",
  },
];

export default cities;
